
//Cart Actions
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const TOGGLE_CART = 'TOGGLE_CART';


//Filter actions
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const SHOW_ALL_BRANDS = 'SHOW_ALL_BRANDS';
export const FILTER_MENU_INTERACTION = 'FILTER_MENU_INTERACTION';
export const MAKE_ACTIVE = 'MAKE_ACTIVE';
export const ADD_FILTER_MENU_LIST = 'ADD_FILTER_MENU_LIST';
export const OPEN_FILTER_MENU = 'OPEN_FILTER_MENU';

//Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const ADD_TO_CART_UPDATE_PRODUCTS = 'ADD_TO_CART_UPDATE_PRODUCTS';
export const REMOVE_FROM_CART_UPDATE_PRODUCTS = 'REMOVE_FROM_CART_UPDATE_PRODUCTS';